import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/effect-fade";
import Providers from "@/lib/utils/provider";
import { Toaster } from "@/components/ui/toaster";
import InfoBar from "@/components/InfoBar/infobar";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <Providers>
          <InfoBar />
          <Navbar />
          <div className="min-h-[50vh]"> {children}</div>
          <div className="">
            <Footer />
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
